# Generated by Django 3.2.7 on 2021-09-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Languages',
        ),
        migrations.AlterField(
            model_name='log',
            name='messages',
            field=models.JSONField(blank=True, default={'state': 0}, null=True),
        ),
    ]
