# Generated by Django 3.2.7 on 2021-09-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0002_auto_20210907_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=256, null=True)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256, null=True)),
                ('lang', models.IntegerField()),
                ('menu_log', models.IntegerField()),
            ],
        ),
    ]
