# Generated by Django 3.2.7 on 2021-09-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0003_tguser'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=256, null=True)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256, null=True)),
                ('lang', models.IntegerField(default=1)),
                ('menu_log', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='TgUser',
        ),
    ]
