# Generated by Django 3.2.7 on 2021-09-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0004_auto_20210908_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='menu_log',
            field=models.IntegerField(null=True),
        ),
    ]
