# Generated by Django 3.2.7 on 2021-09-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0005_alter_user_menu_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lang',
            field=models.IntegerField(null=True),
        ),
    ]
