# Generated by Django 3.2.7 on 2021-09-08 08:30

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import tg


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0006_alter_user_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=tg.lang_dict_field)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_main', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(db_index=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='tg.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
